### ISSUE TITLE
Layout ideas

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-legume#1]
I've created a new branch https://github.com/gbif/hp-legume/tree/styling
It is a bunch of little layout changes. You can use them for inspiration for what is possible or ignore them as you see fit.

For convenience I've deployed the changes to a temporary domain so you can see them
https://gbif-demo-hp-legume.netlify.app/

It doesn't change any content, but is an attempt to layout the pages differently.

**home page layout** 
<img width="1438" alt="Screenshot 2021-03-10 at 14 28 45" src="https://user-images.githubusercontent.com/6759267/110636941-2c732100-81ad-11eb-8d4f-1f688af448ea.png">

**Taxonomy section**
<img width="1440" alt="Screenshot 2021-03-10 at 14 29 13" src="https://user-images.githubusercontent.com/6759267/110636976-385ee300-81ad-11eb-990b-e128483a7fdc.png">

**Bean bag issues**
<img width="1438" alt="Screenshot 2021-03-10 at 14 29 01" src="https://user-images.githubusercontent.com/6759267/110637037-47459580-81ad-11eb-9d70-9895b5c57094.png">

**Comment by CaroleSinou** [comment]
That's awesome.
We will certainly use the one you suggested for the Bean Bag Issues.
I like also the taxonomy pages but it creates a wrap of text in the genera table.

**Comment by MortenHofft** [comment]
> I like also the taxonomy pages but it creates a wrap of text in the genera table.

You might want to look at https://hp-theme.gbif-staging.org/markdown#table-overflow
