### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-legume#2]
If you need any help with the home page let me know. Currently what you have is the default, but it can be configured to do more. For inspiration you can look at https://hp-colombian-biodiversity.gbif-staging.org/ 

The intention is that one can build a home page from a [set of blocks](https://hp-theme.gbif-staging.org/layout/compose)

**Comment by CaroleSinou** [comment]
That looks gorgeous! Thanks for the link @MortenHofft.
I'll have a deeper look and let you know if/when we need help. Thanks :)

**Comment by CaroleSinou** [comment]
@MortenHofft I've added stats to the home page, using the GBIF API.
Species and genera counts work well, but occurrences count is not displaying.
I've used this query to fetch the occurrence count:
```
https://api.gbif.org/v1/occurrence/count?taxonKey=5386
```

Any advice on why it is not displayed?

**Comment by MortenHofft** [comment]
Yes, because it only works with json responses. And that endpoint returns text.
`https://api.gbif.org/v1/occurrence/search?taxonKey=5386&limit=0` will work
