### ISSUE TITLE
Add COL pages to menu

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-legume#6]
https://hp-legume.gbif-staging.org/taxonomy/browse
https://hp-legume.gbif-staging.org/taxonomy/search
https://hp-legume.gbif-staging.org/taxonomy/taxon/30032383-2

These pages aren't in any menus, so no one can find them. In the [styling branch](https://github.com/gbif/hp-legume/issues/1) I added them to side menu in a document layout, but how to expose these are up to you.

If these are added to the french part as well, then we need to configure the servers for the taxon pages. To do that @MattBlissett will need to know the urls for any other language versions.

**Comment by MortenHofft** [comment]
Let me know if you want me to add this and if so what the french URLs should be.

**Comment by MortenHofft** [comment]
Hi @acaciamulga 
As discussed on mail I've added CoL to the menus similar to how it was done on the styling branch.

@CaroleSinou I'm not able to do the french translations I'm afraid. I simply left placeholders.
https://github.com/gbif/hp-legume/blob/master/_data/translations.yml#L9
https://github.com/gbif/hp-legume/blob/master/_data/fr/navigation.yml#L12
https://github.com/gbif/hp-legume/blob/master/_data/fr/sidenav.yml#L5
https://github.com/gbif/hp-legume/blame/master/fr/taxonomy/browse.md#L4
https://github.com/gbif/hp-legume/blame/master/fr/taxonomy/search.md#L4
https://github.com/gbif/hp-legume/blame/master/fr/taxonomy/taxon.md#L4

**Comment by CaroleSinou** [comment]
@MortenHofft all pages have been translated to French but page taxon is not working in French version. It land in a 404 page.
I don't understand what is the issue. Any advice?
